//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collection_Order> Collection_Order { get; set; }
        public virtual DbSet<Material_InStorage> Material_InStorage { get; set; }
        public virtual DbSet<Material_Order> Material_Order { get; set; }
        public virtual DbSet<Material_OutStorage> Material_OutStorage { get; set; }
        public virtual DbSet<Order_RecordChart> Order_RecordChart { get; set; }
        public virtual DbSet<Payment_Order> Payment_Order { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<Production_InStorage> Production_InStorage { get; set; }
        public virtual DbSet<Production_OutStorage> Production_OutStorage { get; set; }
        public virtual DbSet<Purchaser> Purchasers { get; set; }
        public virtual DbSet<Sale_Order> Sale_Order { get; set; }
        public virtual DbSet<Sale_OverView> Sale_OverView { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
