//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_RecordChart
    {
        public string Order_ID { get; set; }
        public string Supplier { get; set; }
        public string Phone_Num { get; set; }
        public decimal Order_Money { get; set; }
        public string Operater { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<bool> States { get; set; }
    }
}
