//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public string Pro_ID { get; set; }
        public string Production_Name { get; set; }
        public string Material_Name { get; set; }
        public decimal Diameter { get; set; }
        public decimal Volume { get; set; }
        public string SaleNo { get; set; }
        public string Production_Line { get; set; }
        public int Pro_Num { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
    }
}
