//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Order
    {
        public string Sao_ID { get; set; }
        public string Production_Name { get; set; }
        public int Sao_Num { get; set; }
        public decimal Pro_Price { get; set; }
        public string Remark { get; set; }
    }
}
